PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZMMA_BGMC03-SPART .
    FIELD ZMMA_BGMC03-MCODESD .
    FIELD ZMMA_BGMC03-MCODECS .
    FIELD ZMMA_BGMC03-CHACOD .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZMMA_BGMC03-SPART .
    FIELD ZMMA_BGMC03-MCODESD .
    FIELD ZMMA_BGMC03-MCODECS .
  module detail_pai.
 endchain.
