PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZVSS_TSKLST_PACK CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZVSS_TSKLST_PACK-PLNNR .
    FIELD ZVSS_TSKLST_PACK-PLNAL .
    FIELD ZVSS_TSKLST_PACK-DATUB .
    FIELD ZVSS_TSKLST_PACK-PACKAGE_ID .
    FIELD ZVSS_TSKLST_PACK-ITCAT .
    FIELD ZVSS_TSKLST_PACK-PSTYV .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZVSS_TSKLST_PACK-PLNNR .
    FIELD ZVSS_TSKLST_PACK-PLNAL .
    FIELD ZVSS_TSKLST_PACK-DATUB .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
